### ISSUE TITLE
[WIKI] wiki.gul.es ya no existe

### ISSUE THREAD

**Issue by Patataman** [acaldero/acaldero.github.io#1]
Holi, me ha dado por mirar y he visto que apuntabas a unos enlaces a la wiki del GUL. 

Nos cargamos la wiki porque no sabíamos que había alguien usándola/apuntado a ella... No sé cuándo exáctamente, pero creo que va para 6 años fácil xD

Ahora los enlaces serían: 

- Grabación charla RAID: https://cloud.gul.es/ftp?dir=undefined&path=%2Factividades%2F2006%2Fmarzo%2FRaid&openfile=18684
- Charla virtualización (solo subieron trasparencias al parecer): https://cloud.gul.es/ftp?path=%2Factividades%2F2007%2Fmarzo%2Fvirtualizacion 

PD: Si los enlaces no funcionan es probable que se deba a que la máquina del CPD se ha apagado, estamos viendo a ver si solucionamos esto con la gente de housing

**Comment by acaldero** [comment]
¡ Muchísimas Gracias !
Pues tan pronto pueda actualizo los enlaces !!
